### ISSUE TITLE
Small discussion

### ISSUE THREAD

**Issue by git-toni** [reactabular/selectabular#3]
So I finally had some time to commit code here. Few things to discuss:
1. https://github.com/reactabular/selectabular/blob/master/src/index.js#L19 When `select.none(rows)`, should we delete the `selected` field alltogether(`select.nonefree` implementation) or just set it to '`false`?
2. It could all be implemented via the `actOnFiltered` function ( also `all` and `none`), but I decided to leave it using `map` as it is more straightforward
3. `select.rows` returning both all the rows and the selected ones is indeed not as nice as the rest. Seeing all of them now in conjunction, I'd make `select.rows` also return just the selected ones. Simpler and more coherent with the returns of the other functions.

**Comment by bebraw** [comment]
> 1. https://github.com/reactabular/selectabular/blob/master/src/index.js#L19 When select.none(rows), should we delete the selected field alltogether(select.nonefree implementation) or just set it to 'false?

Set to `false`. I see no harm in that.

> 1. It could all be implemented via the actOnFiltered function ( also all and none), but I decided to leave it using map as it is more straightforward

Fine with me.

> 1. select.rows returning both all the rows and the selected ones is indeed not as nice as the rest. Seeing all of them now in conjunction, I'd make select.rows also return just the selected ones. Simpler and more coherent with the returns of the other functions.

Maybe the problem can be split up somehow. This sort of situation often implies you should have two separate functions and then compose perhaps.

**Comment by git-toni** [comment]
> Maybe the problem can be split up somehow. This sort of situation often implies you should have two separate functions and then compose perhaps.

Ok, and should both (or the three of them, since one is their composition) be exposed via API?
I take back what I said, let's just return both things for now, it would not be KISS at all to expose two new functions just for `rows` and `selectRows` individually.

On a side note, I'll add my name to the `package.json` if that's allright. I forgot to do that :)

**Comment by bebraw** [comment]
> Ok, and should both (or the three of them, since one is their composition) be exposed via API?
> I take back what I said, let's just return both things for now, it would not be KISS at all to expose two new functions just for rows and selectRows individually.

That would give maximum amount of control. Good idea.

> On a side note, I'll add my name to the package.json if that's allright. I forgot to do that :)

Sure.
